from django.urls import path
from .views import (
    ChatroomListView,
    JoinChatroomView,
    ChatroomDetailView,
    AddMemberView,
    UpdateNicknameView,
    ChatroomQuizzesView,
    MarkChatroomReadView,
    MessageCreateView,
    MessageEditView,
    MessageDeleteView,
    MessageReactionView,
    ForwardMessageView,
    ChatroomSearchView,
    ChatroomStatsView,
    AwardStudentView,
    RemoveMemberView,
)

urlpatterns = [
    path('chatrooms/', ChatroomListView.as_view(), name='chatroom-list'),
    path('join/', JoinChatroomView.as_view(), name='join-chatroom'),
    path('chatrooms/<uuid:pk>/messages/', MessageCreateView.as_view(), name='message-create'),
    path('chatrooms/<uuid:pk>/add/', AddMemberView.as_view(), name='add-member'),
    path('chatrooms/<uuid:pk>/add_member/', AddMemberView.as_view(), name='add-member-alt'),
    path('chatrooms/<uuid:pk>/nickname/', UpdateNicknameView.as_view(), name='update-nickname'),
    path('chatrooms/<uuid:pk>/quizzes/', ChatroomQuizzesView.as_view(), name='chatroom-quizzes'),
    path('chatrooms/<uuid:pk>/search/', ChatroomSearchView.as_view(), name='chatroom-search'),
    path('chatrooms/<uuid:pk>/stats/', ChatroomStatsView.as_view(), name='chatroom-stats'),
    path('chatrooms/<uuid:pk>/mark_read/', MarkChatroomReadView.as_view(), name='mark-chatroom-read'),
    path('chatrooms/<uuid:pk>/awards/', AwardStudentView.as_view(), name='chatroom-awards'),
    path('chatrooms/<uuid:pk>/remove_member/', RemoveMemberView.as_view(), name='remove-member'),
    path('chatrooms/<uuid:pk>/', ChatroomDetailView.as_view(), name='chatroom-detail'),
    path('messages/<uuid:msg_id>/edit/', MessageEditView.as_view(), name='message-edit'),
    path('messages/<uuid:msg_id>/delete/', MessageDeleteView.as_view(), name='message-delete'),
    path('messages/<uuid:msg_id>/react/', MessageReactionView.as_view(), name='message-react'),
    path('messages/<uuid:msg_id>/forward/', ForwardMessageView.as_view(), name='message-forward'),
]