# Generated by Django 6.0.3 on 2026-03-13 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_direct_chatroom_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
