# Generated by Django 6.0.3 on 2026-04-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
