# Generated by Django 6.0.3 on 2026-05-11 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='wallpaper',
            field=models.CharField(blank=True, default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='nickname_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nicknames_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='joined_rooms', through='chat.ChatroomMember', through_fields=('chatroom', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_type', models.CharField(choices=[('top_scorer', 'Top Scorer'), ('most_improved', 'Most Improved'), ('perfect_score', 'Perfect Score'), ('quiz_master', 'Quiz Master'), ('fastest_finisher', 'Fastest Finisher'), ('outstanding', 'Outstanding'), ('heart_of_class', 'Heart of Class'), ('participation', 'Participation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='chat.chatroom')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chatroom', 'student', 'award_type', 'given_by')},
            },
        ),
    ]
