# Generated by Django 6.0.3 on 2026-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
    ]
