# Generated by Django 6.0.3 on 2026-03-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_direct_chatroom_photo_and_more'),
        ('quiz', '0002_quizattempt_attempt_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempt_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('flashcard', 'Flashcard')], default='mcq', max_length=20),
        ),
    ]
