# Generated by Django 6.0.4 on 2026-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_alter_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_retakes',
            field=models.IntegerField(default=1, help_text='Maximum number of times a student can retake this quiz'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mpq', 'Multiple Choice Question'), ('true_false', 'True / False'), ('identification', 'Identification'), ('matching', 'Matching')], default='mpq', max_length=20),
        ),
    ]
