# Generated by Django 6.0.3 on 2026-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shared_to_library',
            field=models.BooleanField(default=False),
        ),
    ]
