# Generated by Django 6.0.3 on 2026-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='teacher_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
