# Generated by Django 6.0.3 on 2026-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_quiz', '0002_quizattempt_teacher_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualquiz',
            name='visibility',
            field=models.CharField(choices=[('private', 'Only Me'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
